### ISSUE TITLE
Idears

### ISSUE THREAD

**Issue by soerenmeier** [Quyzi/gpt#90]
- [x] add configuration option to allow the primary or backup header to be invalid #89 
- [x] Make GptDisk generic over it's ReadWrite
- [x] Better error handling #85
- [x] Maybe add a HeaderBuilder (to replace compute_new)
- [ ] Add more tests, For example #73 
- [x] Simplify GptDisks functions (remove, *_safe, *_embedded) work with cfg flags (write_backup, allow_first_usable_last_usable, change)
- [ ] Improve MBR #84
- [ ] Simplify naming, sectory_size, lb, lba, etc...

**Comment by oldgalileo** [comment]
Hey Soeren, I actually started rewriting this library from the ground up. If you're interested (and especially if you have use cases), I'd love to talk more!

**Comment by soerenmeier** [comment]
Hey Galileo, Yeah I'd be interested. As you might have guessed, Chris gave me the right to this repo and i started to refactor some bits. But I'm open for bigger changes.
I'm currently using this library in Production, in a sort of embedded linux setup with buildroot.

Use 1: Installation
For installing the os to a new disk, i create the partitions via this crate.

Use 2: Update
To figure out where the partitions are to override the fs with an update.
